<div class="new-post">
    <div class="title"><input type="text" placeholder="Title" class="title"/></div>
    <div class="body"><textarea></textarea></div>
    <div class="actions"><button>Save Draft</button> <button>Preview</button> <button>Publish</button></div>
</div>
<?php /*<div class="new-post">
    <label>+</label>
    <nav>
        <a href="/new/text">Text</a>
        <a href="/new/text">Image</a>
        <a href="/new/text">Audio</a>
        <a href="/new/text">Video</a>
        <a href="/new/text">Link</a>
    </nav>
    <div class="clear"></div>
</div> */ ?>
